#!/bin/bash

OUTDIR=../results
SIMDIR=../wimax
SIMTIME=30s


SIMTIME_REGEXP='s/^sim-time-limit.*$/sim-time-limit = '${SIMTIME}'/g'
echo 's/^sim-time-limit.*$/sim-time-limit = 3s/g';
echo ${SIMTIME_REGEXP}

echo "SIMDIR=${SIMDIR} OUTDIR=${OUTDIR} SIMTIME=${SIMTIME}"

mkdir -p ${OUTDIR}
cd ${SIMDIR}
perl -pi -e "${SIMTIME_REGEXP}" omnetpp.ini
rm -f *.vec *.log

function simRun
{
    echo -n "Running sim $1: ";
    date
    /usr/bin/time -v -o ${OUTDIR}/$1-time.log ./wimax -r $1 > ${OUTDIR}/$1.log

    mv -f ${SIMDIR}/run$1.vec ${OUTDIR}
    return;
}


simRun 1
simRun 2
simRun 3
simRun 4
simRun 5
simRun 6
simRun 7
simRun 8
simRun 9
simRun 10
