cplusplus {{

// #include "ipv6msg.h"

}};

message IPv6Ra
{


};


// ********************************************************************************
// *** DHCPv6 messages ************************************************************
// ********************************************************************************

message DHCPv6Solicit
{
fields:
    bool rapidCommit;
    bool addrParams;
};

message DHCPv6Advertise
{

};

message DHCPv6Request
{

};

message DHCPv6Reply
{

};

message DHCPv6Confirm
{

};

